discord:
  client_id: DISCORD_CLIENT_ID
  token: DISCORD_TOKEN_HERE
transcripts:
  directory: tmp
  included_context_lines: 2
http:
  bind_address: 0.0.0.0
  base_url: http://localhost:3000
  port: 3000
development: true
database:
  hostname: 127.0.0.1
  port: 15432
  database: <DATABASE>
  username: <DBUSER>
  password: <DBPASS>
importer:
  directory: tmp/transcripts
  wait_time: 60