discord:
  client_id: DISCORD_CLIENT_ID
  token: DISCORD_TOKEN_HERE
transcripts:
  directory: tmp
  included_context_lines: 2
http:
  bind_address: 0.0.0.0
  base_url: http://localhost:3000
  port: 3000
development: false
database:
  path: tmp/development.db
importer:
  path: tmp/transcripts
  wait_time: 60