version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    networks:
      - front
    ports:
      - 15432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data
    restart: "no"
    environment:
      POSTGRES_PASSWORD: rootpassword

volumes:
  postgresData:

networks:
  front:
