// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datasource_raw

var TableNames = struct {
	Episodes               string
	Podcasts               string
	Speakers               string
	Turns                  string
	UtteranceFragmentLinks string
	UtteranceFragments     string
	UtteranceSpeakers      string
	Utterances             string
}{
	Episodes:               "episodes",
	Podcasts:               "podcasts",
	Speakers:               "speakers",
	Turns:                  "turns",
	UtteranceFragmentLinks: "utterance_fragment_links",
	UtteranceFragments:     "utterance_fragments",
	UtteranceSpeakers:      "utterance_speakers",
	Utterances:             "utterances",
}
