// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datasource_raw

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Speaker is an object representing the database table.
type Speaker struct {
	ID             string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	TranscriptName string    `boil:"transcript_name" json:"transcript_name" toml:"transcript_name" yaml:"transcript_name"`
	Name           string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *speakerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L speakerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SpeakerColumns = struct {
	ID             string
	TranscriptName string
	Name           string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	TranscriptName: "transcript_name",
	Name:           "name",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var SpeakerTableColumns = struct {
	ID             string
	TranscriptName string
	Name           string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "speakers.id",
	TranscriptName: "speakers.transcript_name",
	Name:           "speakers.name",
	CreatedAt:      "speakers.created_at",
	UpdatedAt:      "speakers.updated_at",
}

// Generated where

var SpeakerWhere = struct {
	ID             whereHelperstring
	TranscriptName whereHelperstring
	Name           whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperstring{field: "\"speakers\".\"id\""},
	TranscriptName: whereHelperstring{field: "\"speakers\".\"transcript_name\""},
	Name:           whereHelperstring{field: "\"speakers\".\"name\""},
	CreatedAt:      whereHelpertime_Time{field: "\"speakers\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"speakers\".\"updated_at\""},
}

// SpeakerRels is where relationship names are stored.
var SpeakerRels = struct {
	Utterances string
}{
	Utterances: "Utterances",
}

// speakerR is where relationships are stored.
type speakerR struct {
	Utterances UtteranceSlice `boil:"Utterances" json:"Utterances" toml:"Utterances" yaml:"Utterances"`
}

// NewStruct creates a new relationship struct
func (*speakerR) NewStruct() *speakerR {
	return &speakerR{}
}

func (r *speakerR) GetUtterances() UtteranceSlice {
	if r == nil {
		return nil
	}
	return r.Utterances
}

// speakerL is where Load methods for each relationship are stored.
type speakerL struct{}

var (
	speakerAllColumns            = []string{"id", "transcript_name", "name", "created_at", "updated_at"}
	speakerColumnsWithoutDefault = []string{"id", "transcript_name", "name", "created_at", "updated_at"}
	speakerColumnsWithDefault    = []string{}
	speakerPrimaryKeyColumns     = []string{"id"}
	speakerGeneratedColumns      = []string{}
)

type (
	// SpeakerSlice is an alias for a slice of pointers to Speaker.
	// This should almost always be used instead of []Speaker.
	SpeakerSlice []*Speaker
	// SpeakerHook is the signature for custom Speaker hook methods
	SpeakerHook func(context.Context, boil.ContextExecutor, *Speaker) error

	speakerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	speakerType                 = reflect.TypeOf(&Speaker{})
	speakerMapping              = queries.MakeStructMapping(speakerType)
	speakerPrimaryKeyMapping, _ = queries.BindMapping(speakerType, speakerMapping, speakerPrimaryKeyColumns)
	speakerInsertCacheMut       sync.RWMutex
	speakerInsertCache          = make(map[string]insertCache)
	speakerUpdateCacheMut       sync.RWMutex
	speakerUpdateCache          = make(map[string]updateCache)
	speakerUpsertCacheMut       sync.RWMutex
	speakerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var speakerAfterSelectHooks []SpeakerHook

var speakerBeforeInsertHooks []SpeakerHook
var speakerAfterInsertHooks []SpeakerHook

var speakerBeforeUpdateHooks []SpeakerHook
var speakerAfterUpdateHooks []SpeakerHook

var speakerBeforeDeleteHooks []SpeakerHook
var speakerAfterDeleteHooks []SpeakerHook

var speakerBeforeUpsertHooks []SpeakerHook
var speakerAfterUpsertHooks []SpeakerHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Speaker) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Speaker) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Speaker) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Speaker) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Speaker) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Speaker) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Speaker) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Speaker) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Speaker) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range speakerAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSpeakerHook registers your hook function for all future operations.
func AddSpeakerHook(hookPoint boil.HookPoint, speakerHook SpeakerHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		speakerAfterSelectHooks = append(speakerAfterSelectHooks, speakerHook)
	case boil.BeforeInsertHook:
		speakerBeforeInsertHooks = append(speakerBeforeInsertHooks, speakerHook)
	case boil.AfterInsertHook:
		speakerAfterInsertHooks = append(speakerAfterInsertHooks, speakerHook)
	case boil.BeforeUpdateHook:
		speakerBeforeUpdateHooks = append(speakerBeforeUpdateHooks, speakerHook)
	case boil.AfterUpdateHook:
		speakerAfterUpdateHooks = append(speakerAfterUpdateHooks, speakerHook)
	case boil.BeforeDeleteHook:
		speakerBeforeDeleteHooks = append(speakerBeforeDeleteHooks, speakerHook)
	case boil.AfterDeleteHook:
		speakerAfterDeleteHooks = append(speakerAfterDeleteHooks, speakerHook)
	case boil.BeforeUpsertHook:
		speakerBeforeUpsertHooks = append(speakerBeforeUpsertHooks, speakerHook)
	case boil.AfterUpsertHook:
		speakerAfterUpsertHooks = append(speakerAfterUpsertHooks, speakerHook)
	}
}

// One returns a single speaker record from the query.
func (q speakerQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Speaker, error) {
	o := &Speaker{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "datasource_raw: failed to execute a one query for speakers")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Speaker records from the query.
func (q speakerQuery) All(ctx context.Context, exec boil.ContextExecutor) (SpeakerSlice, error) {
	var o []*Speaker

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "datasource_raw: failed to assign all query results to Speaker slice")
	}

	if len(speakerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Speaker records in the query.
func (q speakerQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: failed to count speakers rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q speakerQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "datasource_raw: failed to check if speakers exists")
	}

	return count > 0, nil
}

// Utterances retrieves all the utterance's Utterances with an executor.
func (o *Speaker) Utterances(mods ...qm.QueryMod) utteranceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"utterance_speakers\" on \"utterances\".\"id\" = \"utterance_speakers\".\"utterance_id\""),
		qm.Where("\"utterance_speakers\".\"speaker_id\"=?", o.ID),
	)

	return Utterances(queryMods...)
}

// LoadUtterances allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (speakerL) LoadUtterances(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSpeaker interface{}, mods queries.Applicator) error {
	var slice []*Speaker
	var object *Speaker

	if singular {
		var ok bool
		object, ok = maybeSpeaker.(*Speaker)
		if !ok {
			object = new(Speaker)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSpeaker)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSpeaker))
			}
		}
	} else {
		s, ok := maybeSpeaker.(*[]*Speaker)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSpeaker)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSpeaker))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &speakerR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &speakerR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"utterances\".\"id\", \"utterances\".\"turn_id\", \"utterances\".\"sequence_no\", \"utterances\".\"is_paralinguistic\", \"utterances\".\"start_time\", \"utterances\".\"end_time\", \"utterances\".\"utterance\", \"utterances\".\"created_at\", \"utterances\".\"updated_at\", \"a\".\"speaker_id\""),
		qm.From("\"utterances\""),
		qm.InnerJoin("\"utterance_speakers\" as \"a\" on \"utterances\".\"id\" = \"a\".\"utterance_id\""),
		qm.WhereIn("\"a\".\"speaker_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load utterances")
	}

	var resultSlice []*Utterance

	var localJoinCols []string
	for results.Next() {
		one := new(Utterance)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.TurnID, &one.SequenceNo, &one.IsParalinguistic, &one.StartTime, &one.EndTime, &one.Utterance, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for utterances")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice utterances")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on utterances")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for utterances")
	}

	if len(utteranceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Utterances = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &utteranceR{}
			}
			foreign.R.Speakers = append(foreign.R.Speakers, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Utterances = append(local.R.Utterances, foreign)
				if foreign.R == nil {
					foreign.R = &utteranceR{}
				}
				foreign.R.Speakers = append(foreign.R.Speakers, local)
				break
			}
		}
	}

	return nil
}

// AddUtterances adds the given related objects to the existing relationships
// of the speaker, optionally inserting them as new records.
// Appends related to o.R.Utterances.
// Sets related.R.Speakers appropriately.
func (o *Speaker) AddUtterances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Utterance) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"utterance_speakers\" (\"speaker_id\", \"utterance_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &speakerR{
			Utterances: related,
		}
	} else {
		o.R.Utterances = append(o.R.Utterances, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &utteranceR{
				Speakers: SpeakerSlice{o},
			}
		} else {
			rel.R.Speakers = append(rel.R.Speakers, o)
		}
	}
	return nil
}

// SetUtterances removes all previously related items of the
// speaker replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Speakers's Utterances accordingly.
// Replaces o.R.Utterances with related.
// Sets related.R.Speakers's Utterances accordingly.
func (o *Speaker) SetUtterances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Utterance) error {
	query := "delete from \"utterance_speakers\" where \"speaker_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeUtterancesFromSpeakersSlice(o, related)
	if o.R != nil {
		o.R.Utterances = nil
	}

	return o.AddUtterances(ctx, exec, insert, related...)
}

// RemoveUtterances relationships from objects passed in.
// Removes related items from R.Utterances (uses pointer comparison, removal does not keep order)
// Sets related.R.Speakers.
func (o *Speaker) RemoveUtterances(ctx context.Context, exec boil.ContextExecutor, related ...*Utterance) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"utterance_speakers\" where \"speaker_id\" = $1 and \"utterance_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeUtterancesFromSpeakersSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Utterances {
			if rel != ri {
				continue
			}

			ln := len(o.R.Utterances)
			if ln > 1 && i < ln-1 {
				o.R.Utterances[i] = o.R.Utterances[ln-1]
			}
			o.R.Utterances = o.R.Utterances[:ln-1]
			break
		}
	}

	return nil
}

func removeUtterancesFromSpeakersSlice(o *Speaker, related []*Utterance) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Speakers {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Speakers)
			if ln > 1 && i < ln-1 {
				rel.R.Speakers[i] = rel.R.Speakers[ln-1]
			}
			rel.R.Speakers = rel.R.Speakers[:ln-1]
			break
		}
	}
}

// Speakers retrieves all the records using an executor.
func Speakers(mods ...qm.QueryMod) speakerQuery {
	mods = append(mods, qm.From("\"speakers\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"speakers\".*"})
	}

	return speakerQuery{q}
}

// FindSpeaker retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSpeaker(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Speaker, error) {
	speakerObj := &Speaker{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"speakers\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, speakerObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "datasource_raw: unable to select from speakers")
	}

	if err = speakerObj.doAfterSelectHooks(ctx, exec); err != nil {
		return speakerObj, err
	}

	return speakerObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Speaker) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("datasource_raw: no speakers provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(speakerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	speakerInsertCacheMut.RLock()
	cache, cached := speakerInsertCache[key]
	speakerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			speakerAllColumns,
			speakerColumnsWithDefault,
			speakerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(speakerType, speakerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(speakerType, speakerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"speakers\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"speakers\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "datasource_raw: unable to insert into speakers")
	}

	if !cached {
		speakerInsertCacheMut.Lock()
		speakerInsertCache[key] = cache
		speakerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Speaker.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Speaker) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	speakerUpdateCacheMut.RLock()
	cache, cached := speakerUpdateCache[key]
	speakerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			speakerAllColumns,
			speakerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("datasource_raw: unable to update speakers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"speakers\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, speakerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(speakerType, speakerMapping, append(wl, speakerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to update speakers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: failed to get rows affected by update for speakers")
	}

	if !cached {
		speakerUpdateCacheMut.Lock()
		speakerUpdateCache[key] = cache
		speakerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q speakerQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to update all for speakers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to retrieve rows affected for speakers")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SpeakerSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("datasource_raw: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), speakerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"speakers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, speakerPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to update all in speaker slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to retrieve rows affected all in update all speaker")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Speaker) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("datasource_raw: no speakers provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(speakerColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	speakerUpsertCacheMut.RLock()
	cache, cached := speakerUpsertCache[key]
	speakerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			speakerAllColumns,
			speakerColumnsWithDefault,
			speakerColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			speakerAllColumns,
			speakerPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("datasource_raw: unable to upsert speakers, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(speakerPrimaryKeyColumns))
			copy(conflict, speakerPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"speakers\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(speakerType, speakerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(speakerType, speakerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "datasource_raw: unable to upsert speakers")
	}

	if !cached {
		speakerUpsertCacheMut.Lock()
		speakerUpsertCache[key] = cache
		speakerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Speaker record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Speaker) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("datasource_raw: no Speaker provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), speakerPrimaryKeyMapping)
	sql := "DELETE FROM \"speakers\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to delete from speakers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: failed to get rows affected by delete for speakers")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q speakerQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("datasource_raw: no speakerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to delete all from speakers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: failed to get rows affected by deleteall for speakers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SpeakerSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(speakerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), speakerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"speakers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, speakerPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: unable to delete all from speaker slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "datasource_raw: failed to get rows affected by deleteall for speakers")
	}

	if len(speakerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Speaker) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSpeaker(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SpeakerSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SpeakerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), speakerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"speakers\".* FROM \"speakers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, speakerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "datasource_raw: unable to reload all in SpeakerSlice")
	}

	*o = slice

	return nil
}

// SpeakerExists checks if the Speaker row exists.
func SpeakerExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"speakers\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "datasource_raw: unable to check if speakers exists")
	}

	return exists, nil
}
