// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datasource_raw

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Episodes", testEpisodesUpsert)

	t.Run("Podcasts", testPodcastsUpsert)

	t.Run("Speakers", testSpeakersUpsert)

	t.Run("Turns", testTurnsUpsert)

	t.Run("Utterances", testUtterancesUpsert)
}
